#region     [personal info configuration]
$git_username = "chencyu"
$git_useremail = "chencyu.personal@gmail.com"
#endregion  [personal info configuration]

if (-Not (Get-Command vim))
{
    winget install --id vim.vim
    if (-Not (Test-Path -Path "$HOME/.vim_runtime"))
    {
        git clone --depth=1 "https://github.com/amix/vimrc.git" "$HOME/.vim_runtime"
        Write-Output "set nu" >> "$HOME/.vim_runtime/my_configs.vim"
        Write-Output "set mouse=a" >> "$HOME/.vim_runtime/my_configs.vim"

        Write-Output @(
            "`" DO NOT EDIT THIS FILE"
            "`" Add your own customizations in ~/.vim_runtime/my_configs.vim"
            "set runtimepath+=~/.vim_runtime"
            "source ~/.vim_runtime/vimrcs/basic.vim"
            "source ~/.vim_runtime/vimrcs/filetypes.vim"
            "source ~/.vim_runtime/vimrcs/plugins_config.vim"
            "source ~/.vim_runtime/vimrcs/extended.vim"
            "try"
            "source ~/.vim_runtime/my_configs.vim"
            "catch"
        ) > "$HOME/.vimrc"

    }
}

if (-Not (Get-Command git))
{
    winget install --id Git.Git
    git config --global user.email "$git_useremail"
    git config --global user.name "$git_username"
    git config --global core.autocrlf false
}
